- name: Setting Facts
  set_fact:
    fipewatcher_backend_config: "{{ solution.application.fipewatcher_backend }}"

- name: Deploying Fipewatcher-Backend 
  include_role:
    name: kube-install
  vars:
    service_config: "{{ fipewatcher_backend_config }}"